name: Post publications to Bluesky

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  post_to_bluesky:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas numpy pyzotero requests beautifulsoup4 grapheme pytz atproto==0.0.56

      - name: Run Python Script
        env:
          BLUESKY_PASSWORD: ${{ secrets.BLUESKY_PASSWORD }}
        run: |
          python bluesky_posts/bluesky_publications_bot.py